name: Silu X - Global Wealth Management
favicon: null
layout_spectrum: 0.71114207431674
typography_spectrum: 0.822569788666442
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8720562350936234
  lightness: 0.3789181688334793
  saturation: 0.9196166687179357
  rhythmicContrast: 0.5182120243553072
purpose: []
